# Generated by Django 5.1.6 on 2025-02-06 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_users_userssn'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userssn',
            table='userssn',
        ),
    ]
